### PR TITLE
Fix for metadata feature

### PR DESCRIPTION
**Pull request by drakakisgeo**
With this change I was able to use Meta info.

### CODE REVIEW

**Comment by drakakisgeo** [comment]
Is there a reason other than "not enough time to review this" for not merging this PR ?

**Comment by drakakisgeo** [comment]
Hey @atheken , any idea why this PR is not good to go?

**Comment by izio38** [comment]
I had the support yesterday, they said they are working on a fix... But all they have to do is accept this PR...

**Comment by fagai** [comment]
I am also waiting for acceptance...  @atheken

**Comment by gilesa** [comment]
@atheken can you please review and merge? This functionality is critical for being able to take advantage of all Postmark's features. Aside from some indentation inconsistencies, the change look ok to me.

**Comment by aconital** [comment]
any update on when this PR will be accepted?

**Comment by aconital** [comment]
The code submitted by @izio38 might be better since it handles multiple tags https://github.com/wildbit/swiftmailer-postmark/issues/20#issuecomment-539439778

**Comment by izio38** [comment]
ref #23

**Comment by atheken** [comment]
As mentioned in #23, we're trying to defer most of this work to the API so that customers don't need to update their clients as frequently/when we add new functionality. This is now built in to the API, so no special handling is required by this transport.

**Pull request closed without merging**
