### PR TITLE
Added support for Guzzle 7 and PHP 7.3-7.4

### PR DESCRIPTION
**Pull request by GrahamCampbell**
I've also corrected your code style, most notably, a bunch of tabs instead of spaces, in some of the files. Additionally, you were missing a license file (composer.json indicated MIT), and repository field was miss-used in in composer.json file (fixed).

---

NB This PR retains support for Guzzle 6 too, and also PHP 7.0-7.2. We end up with Guzzle 6 and 7 support, and PHP 7.0-7.4 support.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by jesperbjerke** [comment]
@atheken is anyone able to merge this pull request?

**Comment by GrahamCampbell** [comment]
Friendly ping @atheken. :)

**Comment by GrahamCampbell** [comment]
I suppose this package is dead. Someone should fork it to replace it.

**Comment by vladsandu** [comment]
@GrahamCampbell thank you for contributing to this library and we apologize for the great delay in getting to review this PR.

If you are still interested in contributing, would it be possible to restore the deleted forked repository and re-create/re-open this PR? If possible, I would be more than happy to get this merged and released shortly after.

**Comment by mfn** [comment]
@vladsandu I took the liberty and created a … slightly smaller… PR ;) => https://github.com/wildbit/swiftmailer-postmark/pull/37

I totally understand @GrahamCampbell with all the changes in this PR, but let's take smaller steps, now that there's activity again.

**Comment by GrahamCampbell** [comment]
If someone else wants to take over from where I left off, feel free. I don't have time to do anything more, sorry.

**Comment by mfn** [comment]
@GrahamCampbell awesome and thanks for showing the way 🙏

**Pull request closed without merging**
